devices:
  - ip: 172.20.20.11
    type: ios
    username: admin
    password: autonetops
  - ip: 172.20.20.12
    type: ios
    username: admin
    password: autonetops
  - ip: 172.20.20.13
    type: ios
    username: admin
    password: autonetops