r2:
  conn:
    host: r2
    device_type: cisco_ios
    username: admin
    password: autonetops
    port: 22
  config: |
    route-map MED permit 10
      set metric 100
    !
    router bgp 200
      neigh 192.168.12.1 route-map MED out
    !
    clear ip bgp * out