install: 
	python setup.py install

uninstall: 
	pip uninstall -y autonetops

clean:
	python setup.py clean --all 
	rm -Rf dist
	rm -Rf *.egg-info
	rm -Rf autonetops/__pycache__
	rm -Rf autonetops/utils/__pycache__
	